apiVersion: v1
kind: Service
metadata:
  name: shibuya-api-{{ .Values.context }}
  labels:
    {{- range .Values.apiserver.labels }}
    {{.key }}: {{.value }}
    {{- end }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    {{- range .Values.apiserver.labels }}
    {{.key }}: {{.value }}
    {{- end }}
